[build]
  publish = "public"
  command = "zola build"

[build.environment]
  ZOLA_VERSION = "0.20.0"

[[redirects]]
  from = "https://cosoteca.obrero.ar/*"
  to = "https://obrero.ar/cosoteca/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://guiso.obrero.ar/*"
  to = "https://sublevar-guiso.netlify.app/:splat"
  status = 200
  force = true
